version: '3'
services:
    api:
        build: ./api
        ports:
            - "8080:8080"
        networks:
            - api-tier
        environment:
            - IP_DB=db
            - API_PORT=8080
            - DB_USER=postgres
            - DB_PASSWORD=password
            - DB_NAME=postgres
            - DB_HOST=db
            - DB_PORT=5432
        restart: on-failure
        depends_on:
            - db
    db:
        container_name: "db"
        image: "postgres:latest"
        networks:
            - api-tier
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
        expose:
            - "5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=postgres
        restart: on-failure

networks:
    api-tier:

volumes:
    db-data: